### PR TITLE
Update runtime to 5.13, and update patches.

### PR DESCRIPTION
**Pull request by corecontingency**
Updated the runtime to 5.13, the kiwix dependencies, and patches. It seems that xapian_sys_types.patch is not being automatically updated by kiwixbot, so I updated it too. Hope this works!

### CODE REVIEW

**Comment by corecontingency** [comment]
Hmmm.... first the build failed complaining about an unknown QT module. Reverting to runtime 5.12 lets it build but when installed, doesn't run, just crashes. Any suggestions are welcome.

**Comment by eszlari** [comment]
```
WARNING: Project ERROR: Unknown module(s) in QT: webenginewidgets
```
https://bugs.kde.org/show_bug.cgi?id=414175

**Comment by kelson42** [comment]
What stops us to move on here? https://bugs.kde.org/show_bug.cgi?id=414175 has been fixed months ago!

**Comment by eszlari** [comment]
Provide a PR with a move to https://github.com/flathub/io.qt.qtwebengine.BaseApp ?

**Pull request closed without merging**
