### PR TITLE
Remove flathub.json to enable aarch64

### PR DESCRIPTION
**Pull request by hfiguiere**
I have tested the aarch64 build on RaspberryPi.

### CODE REVIEW

**Comment by hfiguiere** [comment]
For the record commit message show it was disabled because of QtWebEngine, but for a few release it's not a problem anymore.

**Comment by hfiguiere** [comment]
Can I just merge this now? @mgautierfr

**Comment by mgautierfr** [comment]
As said here : https://github.com/flathub/org.kiwix.desktop/pull/6#issuecomment-866130552 our CI (kiwix/kiwix-build) will regenerate the json file and push it to this repository.
Merging this PR is at best useless.

I don't know what is the policy on flathub about the QA of the application.
We may enable aarch64 here (update the json template in our ci) but nothing on all our tool chain is testing this (even not the compilation). We do not provide any support on this architecture.

@kelson42 what do you think about this ?

**Comment by kelson42** [comment]
It is true that upstrean, in Kiwix project, we don't test/release Kiwix Desktop for aarch64. But libkiwix is distributed for aarch64, at least the Android binding. Kiwix Desktop for Linux is as well provided for aarch64 in Debian. Therefore, probably it just works out of the box. If @hfiguiere is commited to help supporting aarch64 for Kiwix Desktop here on Flathub this is fine to me. We can merge.

**Comment by mgautierfr** [comment]
> As said here : #6 (comment) our CI (kiwix/kiwix-build) will regenerate the json file and push it to this repository.
Merging this PR is at best useless.

By bad. kiwix-build rewrite only `org.kiwix.desktop.json`. `flathub.json` "source" is this repository.
So if we agree we have to merge this PR. We have nothing to do on kiwix-build side.
Sorry for this too quick comment.

**Comment by kelson42** [comment]
@mgautierfr Got it, let do the change upstream and close this PR once this is done. @hfiguiere Thx again for your patch.

**Comment by hfiguiere** [comment]
So I can click merge, right?

**Comment by kelson42** [comment]
@hfiguiere Yes, this should be merged. Sorry, it got forgotten.

**Pull request merged**
