### PR TITLE
Update runtime, add build-options to make it work with QtWebEngine

### LINKED ISSUE #3: Update runtime to 5.13

### PR DESCRIPTION
**Pull request by lionirdeadman**
Fix #3

### CODE REVIEW

**Comment by hfiguiere** [comment]
btw trying to build this on `aarch64`. not blocking, but if it works, then we can reenable (in a future PR)

**Comment by hfiguiere** [comment]
It actually works without change. Just need to remove the `flathub.json`

**Comment by hfiguiere** [comment]
For the record, the original reason:

https://github.com/kiwix/kiwix-desktop/issues/221

It said `arm` though, while this is `aarch64` (the former isn't supported anyway).

**Comment by mgautierfr** [comment]
The content of this repository is generated by https://github.com/kiwix/kiwix-build

The fix should go there.

**Comment by lionirdeadman** [comment]
Ah... I can get most of the way there but there seems to not be a system for env variables in build-options. That seems be quite a bit harder as a result.

**Comment by hfiguiere** [comment]
but we can merge this here, right?

**Comment by mgautierfr** [comment]
This repository content is generated by kiwix-build, if we merge this PR, at best the content will be lost, at worst we will have conflict to resolve by hand and which will make the automatic build fail.

**Comment by hfiguiere** [comment]
The problem is your tool has gaps 

https://github.com/flathub/org.kiwix.desktop/pull/6#issuecomment-861639528

So how can it be solved? This package use a deprecated runtime.

**Comment by mgautierfr** [comment]
> So how can it be solved? This package use a deprecated runtime.

This has to be fixed in our tool.

**Comment by mgautierfr** [comment]
The kiwix-build tool has been updated (https://github.com/kiwix/kiwix-build/commit/afd17b2986284333d9eb694542298471a86bc421).
The generated manifest is now the the same than this PR. Next release of kiwix-desktop on our side will generate a new version of the manifest.
I'm merging this PR to trigger a new flatpak build right now.

Thanks @lionirdeadman

**Review by mgautierfr — APPROVED** [review]

**Comment by hfiguiere** [comment]
thanks!

**Comment by hfiguiere** [comment]
Does your script also push the flathub.json? Because this build works fine on `aarch64` (it's just disabled)

**Comment by mgautierfr** [comment]
The CI also push the flathub when we do a release or a new "build" (following a change in our dependency stack)

We don't test on aarch64 in our CI so we disable it as there is no qa at all.
I'm not sure we/you want untested application on flathub.

**Comment by hfiguiere** [comment]
It's clear that if you don't build it you won't test it.

**Pull request merged**
